### ISSUE TITLE
Setting up Kanban Board

### ISSUE THREAD

**Issue by amare1990** [J2ZROMERO/Ruby-group-capstone#55]
- [ ] [Repository link](https://github.com/users/J2ZROMERO/projects/4/views/1)
- [ ] This team has 4 people 

**Team members assigned:** 

- Team member#1- @J2ZROMERO
- Team member#2 - @Oklukeok 
- Team member#3 - @amare1990 
- Team member#4 - @gandradep

**Comment by Mihndim2020** [comment]
### Hi Team, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good job with issue summary
:heavy_check_mark: Good job with task distribution

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)

# Status: Requires Changes ♻️
_Check the comments below._

- [ ] Please update you project link so that when clicked on, it takes you directly to the [kanban board](https://github.com/users/J2ZROMERO/projects/2/views/1) not the repository. 
- [ ] It will be nice to name the first column of your `Kanban board`  as `Todo` not `No Status` as your are supposed to follow [the template](https://github.com/microverseinc/curriculum-ruby/projects/1) provided
- [ ] Please make sure all your tasks have a proper tasks description, as this will be helpful during the implementation phase, as this will give information of what needs to be implemented exactly. Please make sure all the tasks have a task description. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by J2ZROMERO** [comment]
Thanks, @Mihndim2020  for your feedback. We will apply changes.

**Comment by prolajumokeoni** [comment]
Hi @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- Kanban board setup is complete 👏🏿  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
